name: Kalpesh Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore COSECWORKFLOW.sln

      - name: Build Application
        run: dotnet build COSECWORKFLOW.sln --configuration Release --no-restore

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-build
          path: bin/Release/net8.0/
          retention-days: 5  # Store the artifact for 5 days

  download:
    runs-on: windows-latest
    needs: build  # This ensures the build job runs first

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dotnet-build
          path: downloaded-artifacts/  # Store the artifacts in a separate folder

      - name: List Downloaded Files (Debugging Purpose)
        run: Get-ChildItem -Path 'downloaded-artifacts' -Recurse
