

name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

   
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0


   # - name: Set up .NET
    #  uses: actions/setup-dotnet@v3
     # with:
      #  dotnet-version: '7.0'  # Use the version you are targeting, e.g., '6.0', '7.0'

   # - name: Restore dependencies
#      run: dotnet restore  # Restore NuGet dependencies

  #  - name: Build the application
   #   run: dotnet build --configuration Release  # Build the app in Release mode

    #- name: Run tests (if applicable)
     # run: dotnet test  # Run unit tests if they exist

    #- name: Publish the application
    #  run: dotnet publish -c Release -r win-x64 --self-contained true --output ./publish

  deploy:
    runs-on: windows-latest  # You can specify the deployment server/target environment

    steps:
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: ./publish





   



  
